-- Papirskema (5.10.2026, Jonn). Kør UDEN FOR ARBEJDSTID, i ét hug: tilføjelsen af opgave_nr
-- omskriver tabellen instances (ca. 18.500 rækker) og låser den i nogle sekunder.
-- Kun Jammerbugts database. Kundedatabasen har ikke kolonnen, og skemaet udelader så bare «Nr.».
--
-- Hvorfor en identitetskolonne og ikke en kolonne, der opdateres bagefter: omskrivningen giver
-- alle eksisterende rækker et nummer UDEN at røre dem som opdateringer. En opdatering af 18.500
-- rækker ville give 18.500 poster i ændringsloggen og 18.500 realtime-hændelser til hver åben fane.
-- Numrene på de gamle opgaver følger rækkernes fysiske rækkefølge — de er unikke, ikke kronologiske.
--
-- Rulles tilbage med:
--   drop table public.papirskema_linjer;
--   alter table public.instances drop column opgave_nr;   (og view'et lægges tilbage uden kolonnen)

alter table public.instances add column if not exists opgave_nr bigint generated by default as identity;
create unique index if not exists instances_opgave_nr_key on public.instances (opgave_nr);

-- Visningen planlægningsappen henter fra. Kolonnen står sidst, så create or replace er tilladt.
create or replace view public.instances_let as
 SELECT id, template_id, title, type, week, day, deadline, duration, status, video_url, customer_id,
    po_number, warning, assignees, time_log, required_skills, customer_name, address_text,
    access_instructions, contract_type, invoice_ready, start_date, expiry_date, dinero_exported, year,
    block_group_id, dinero_synced, include_in_auto, off_schedule, on_schedule, completed_by,
    completed_at, scheduled_time, assigned_employee_id, completed_by_employee, pricing_type,
    fixed_price, checklist_template_ids, extra_items, deleted_at, dinero_contact_guid,
    nexus_confirmed, created_at, needs_key_pickup, km_fra_adresse, km_tur_retur, km_anslaaet,
    oplaering_medarbejdere, tid_fordeling,
    jsonb_array_length(COALESCE(checklist, '[]'::jsonb)) AS checklist_antal,
    ( SELECT (count(*))::integer AS count
        FROM jsonb_array_elements(COALESCE(i.checklist, '[]'::jsonb)) e(value)
       WHERE (((e.value ->> 'done'::text))::boolean IS TRUE)) AS checklist_udfoert,
    telefon, email, kontaktperson, aflyst_grund, aflyst_forklaring, aflyst_tid,
    aflyst_faktureret, aflyst_assignees, opgave_nr
   FROM instances i;
alter view public.instances_let set (security_invoker = true);

-- Det, kontoret har godkendt fra et papirskema. Tiden ligger på opgaven (time_log); her står
-- det, der ikke må gå til løn: kilometer, medarbejderen skrev, set mod systemets.
create table if not exists public.papirskema_linjer (
  id           uuid primary key default gen_random_uuid(),
  oprettet     timestamptz not null default now(),
  godkendt_af  text,
  employee_id  text not null,
  instance_id  text,
  opgave_nr    bigint,
  dato         date,
  minutter     integer,
  km_papir     numeric,
  km_system    numeric,
  afvigelse_km numeric,
  afviger      boolean not null default false,
  note         text,
  constraint papirskema_linjer_en_pr_opgave unique (employee_id, instance_id)
);
alter table public.papirskema_linjer enable row level security;
create policy papirskema_admin_all on public.papirskema_linjer
  for all to authenticated using ((select is_admin())) with check ((select is_admin()));
revoke all on public.papirskema_linjer from public, anon;
grant select, insert, update, delete on public.papirskema_linjer to authenticated, service_role;

-- Morgentjekket melder nye felter, indtil nogen har taget stilling.
insert into public.persondata_register (tabel, kolonne, persondata, daekket_af, bemaerkning) values
  ('instances', 'opgave_nr', false, null, 'Fortløbende opgavenummer, trykkes på det udprintede timeskema.'),
  ('papirskema_linjer', 'id', false, null, null),
  ('papirskema_linjer', 'oprettet', false, null, null),
  ('papirskema_linjer', 'godkendt_af', true, 'medarbejdere', 'E-mail på planlæggeren, der godkendte linjen.'),
  ('papirskema_linjer', 'employee_id', true, 'medarbejdere', 'Hvem skemaet gælder.'),
  ('papirskema_linjer', 'instance_id', true, 'begge', 'Opgaven linjen hører til.'),
  ('papirskema_linjer', 'opgave_nr', false, null, null),
  ('papirskema_linjer', 'dato', true, 'medarbejdere', null),
  ('papirskema_linjer', 'minutter', true, 'medarbejdere', 'Tiden fra papirskemaet. Selve tiden ligger også i instances.time_log.'),
  ('papirskema_linjer', 'km_papir', true, 'medarbejdere', 'Kilometer, medarbejderen selv skrev på papiret. Bruges kun til at sammenligne med systemets; løn bruger systemets.'),
  ('papirskema_linjer', 'km_system', true, 'medarbejdere', 'Systemets kilometer for samme linje, på godkendelsestidspunktet.'),
  ('papirskema_linjer', 'afvigelse_km', true, 'medarbejdere', null),
  ('papirskema_linjer', 'afviger', true, 'medarbejdere', 'Om forskellen var så stor, at kontoret skulle se på den.'),
  ('papirskema_linjer', 'note', true, 'medarbejdere', null)
on conflict (tabel, kolonne) do nothing;
